const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");

test("3D source integrates every gameplay module", () => {
  const source = fs.readFileSync(path.join(root, "game-3d.source.js"), "utf8");
  for (const moduleName of ["player-visual", "city-stream", "combat-director", "vfx"]) {
    assert.match(source, new RegExp(`\\./game/${moduleName}\\.js`));
  }
  assert.match(source, /event\.code === "Enter"[^\n]+fire\(\)/, "Enter should fire the player weapon");
  assert.match(source, /CatmullRomCurve3/, "player projectiles should use a curved banana body");
  assert.match(source, /isBananaProjectile = true/, "player projectiles should be identifiable as bananas");
});

test("opening briefing establishes the mission", () => {
  const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
  assert.match(html, /<title>Monkey See, Monkey Pew<\/title>/);
  assert.match(html, /Commander Vesper/);
  assert.match(html, /only one who can save this planet/i);
  assert.match(html, /assets\/commander-vesper-v1\.png/);
});

test("standalone release is self-contained", () => {
  const standalone = fs.readFileSync(path.join(root, "monkey-no-fly-zone-standalone.html"), "utf8");
  assert.match(standalone, /Self-contained build generated by scripts\/build-standalone\.js/);
  assert.match(standalone, /Embedded assets:/);
  assert.match(standalone, /data:image\/(?:jpeg|png);base64,/);
  assert.doesNotMatch(standalone, /(?:\.\/)?assets\/[A-Za-z0-9._/-]+\.(?:jpe?g|png)/i);
});
